### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by fabaff** [jeroenterheerdt/python-egardia#1]
Please add timeouts to all requests. Like [here](https://github.com/jeroenterheerdt/python-egardia/blob/master/src/pythonegardia/egardiadevice.py#L63).

**Comment by fabaff** [comment]
Should be addressed before we merge https://github.com/home-assistant/home-assistant/pull/8389

**Comment by jeroenterheerdt** [comment]
Added timeouts to all requests.

**Comment by fabaff** [comment]
Thanks
