### ISSUE TITLE
Woonveilig GATE-03 support

### ISSUE THREAD

**Issue by elpirato83** [jeroenterheerdt/python-egardia#11]
Is it possible to supply Woonveilig/Egardia GATE-03 support in Home Assistant? When I add the current Egardia plugin I get the following error messages in the HA log:

> Error on device update!
> 
> Traceback (most recent call last):
>   File "/usr/src/app/homeassistant/helpers/entity_component.py", line 217, in async_add_entity
>     yield from entity.async_device_update(warning=False)
>   File "/usr/src/app/homeassistant/helpers/entity.py", line 306, in async_device_update
>     yield from self.hass.async_add_job(self.update)
>   File "/usr/local/lib/python3.6/asyncio/futures.py", line 332, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
>     future.result()
>   File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
>     raise self._exception
>   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/app/homeassistant/components/alarm_control_panel/egardia.py", line 173, in update
>     self.parsestatus(status)
>   File "/usr/src/app/homeassistant/components/alarm_control_panel/egardia.py", line 165, in parsestatus
>     if status.upper() == k][0])
> IndexError: list index out of range

GET http://[ip address]/action/panelCondGet in Postman gives the following result:

> {
>     "updates": {
>         "mode_a1": "Disarm",
>         "mode_a2": "Disarm",
>         "battery_ok": "1",
>         "battery": "Normal",
>         "tamper_ok": "1",
>         "tamper": "N/A",
>         "interference_ok": "1",
>         "interference": "Normal",
>         "ac_activation_ok": "1",
>         "ac_activation": "Normal",
>         "sys_in_inst": "System in maintenance",
>         "rssi": "1",
>         "sig_gsm_ok": "1",
>         "sig_gsm": "N/A"
>     },
>     "forms": {
>         "pcondform1": {
>             "mode": "0",
>             "f_arm": "0"
>         },
>         "pcondform2": {
>             "mode": "0",
>             "f_arm": "0"
>         }
>     }
> }

GET http://[ip address]/action/deviceListGet in Postman gives the following result:

> {
>     "senrows": [
>         {
>             "area": 1,
>             "zone": 3,
>             "type": 4,
>             "type_f": "Door Contact",
>             "name": "Schuifpui rechts",
>             "cond": "",
>             "cond_ok": "1",
>             "battery": "",
>             "battery_ok": "1",
>             "tamper": "",
>             "tamper_ok": "1",
>             "bypass": "No",
>             "temp_bypass": "0",
>             "rssi": "Strong, 9",
>             "status": "Door Close",
>             "id": "RF:00e76001",
>             "su": 1
>         },
>         {
>             "area": 1,
>             "zone": 6,
>             "type": 4,
>             "type_f": "Door Contact",
>             "name": "Voordeur",
>             "cond": "",
>             "cond_ok": "1",
>             "battery": "",
>             "battery_ok": "1",
>             "tamper": "",
>             "tamper_ok": "1",
>             "bypass": "No",
>             "temp_bypass": "0",
>             "rssi": "Strong, 9",
>             "status": "Door Close",
>             "id": "RF:00f4fa99",
>             "su": 1
>         },
>         {
>             "area": 1,
>             "zone": 5,
>             "type": 15,
>             "type_f": "Keypad",
>             "name": "Voordeur",
>             "cond": "",
>             "cond_ok": "1",
>             "battery": "",
>             "battery_ok": "1",
>             "tamper": "",
>             "tamper_ok": "1",
>             "bypass": "No",
>             "temp_bypass": "0",
>             "rssi": "Strong, 9",
>             "status": "",
>             "id": "RF:0279a099",
>             "su": 0
>         },
>         {
>             "area": 1,
>             "zone": 2,
>             "type": 9,
>             "type_f": "IR",
>             "name": "Woonkamer achterzijde",
>             "cond": "",
>             "cond_ok": "1",
>             "battery": "",
>             "battery_ok": "1",
>             "tamper": "",
>             "tamper_ok": "1",
>             "bypass": "No",
>             "temp_bypass": "0",
>             "rssi": "Strong, 9",
>             "status": "",
>             "id": "RF:0409d999",
>             "su": 1
>         },
>         {
>             "area": 1,
>             "zone": 1,
>             "type": 9,
>             "type_f": "IR",
>             "name": "Woonkamer voorzijde",
>             "cond": "",
>             "cond_ok": "1",
>             "battery": "",
>             "battery_ok": "1",
>             "tamper": "",
>             "tamper_ok": "1",
>             "bypass": "No",
>             "temp_bypass": "0",
>             "rssi": "Strong, 9",
>             "status": "",
>             "id": "RF:040be967",
>             "su": 1
>         },
>         {
>             "area": 1,
>             "zone": 4,
>             "type": 2,
>             "type_f": "Remote Controller",
>             "name": "Bewoner",
>             "cond": "",
>             "cond_ok": "1",
>             "battery": "",
>             "battery_ok": "1",
>             "tamper": "",
>             "tamper_ok": "1",
>             "bypass": "No",
>             "temp_bypass": "0",
>             "rssi": "N/A",
>             "status": "",
>             "id": "RF:0434f987",
>             "su": 0
>         }
>     ]
> }

My Python programming skills are not good enough (yet) to debug/change the code. If you need some more info about the GATE-03 system or if I need to run some more tests, please send me a message.

**Comment by jeroenterheerdt** [comment]
thanks for asking - I do not have access to a gate-03 device, but we should be able to make it work. Can you post the output of action/sensorListGet as well?

**Comment by elpirato83** [comment]
Postman output of http://[ip address]/action/sensorListGet is:

`<html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"/><link rel="stylesheet" type="text/css" href="/css/main.css"/><title>Document Error: Site or Page Not Found</title></head><body><h2>Access Error: Site or Page Not Found</h2><a href="/index.htm" target="_top">Go to home</a></body></html>`

**Comment by jeroenterheerdt** [comment]
Can you please clone this repo to somewhere where you can run Python3 (outside of HASS preferably) and run `python test_egardiadevice.py IP PORT USERNAME PASSWORD GATE-03` (replace IP, PORT, USERNAME and PASSWORD with your own values)? Please paste the output here. Thanks.

**Comment by elpirato83** [comment]
The requested output:

> Traceback (most recent call last):
>   File "test_egardiadevice.py", line 36, in <module>
>     main()
>   File "test_egardiadevice.py", line 31, in main
>     eg = e.EgardiaDevice(host, port, username, password, "", version)
>   File "/home/arjan/python-egardia/src/pythonegardia/egardiadevice.py", line 45, in __init__
>     self._sensors = self.getsensors()
>   File "/home/arjan/python-egardia/src/pythonegardia/egardiadevice.py", line 100, in getsensors
>     sensord = self.parseJson(sensors)
>   File "/home/arjan/python-egardia/src/pythonegardia/egardiadevice.py", line 183, in parseJson
>     data = json.loads(crappy_json, strict=False)
>   File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
>     return cls(encoding=encoding, **kw).decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

**Comment by elpirato83** [comment]
2nd time I run the test I get this output:

> ('getstate output ', u'S')
> ('getsensors output ', {u'RF:00e76910': {u'status': u'Door Close', u'name': u'Schuifpui rechts', u'zone': 3, u'area': 1, u'battery': u'', u'tamper': u'', u'cond_ok': u'1', u'su': 1, u'id': u'RF:00e76910', u'cond': u'', u'bypass': u'No', u'tamper_ok': u'1', u'rssi': u'Strong, 9', u'temp_bypass': u'0', u'type': 4, u'battery_ok': u'1', u'type_f': u'Door Contact'}, u'RF:040be130': {u'status': u'', u'name': u'Woonkamer voorzijde', u'zone': 1, u'area': 1, u'battery': u'', u'tamper': u'', u'cond_ok': u'1', u'su': 1, u'id': u'RF:040be130', u'cond': u'', u'bypass': u'No', u'tamper_ok': u'1', u'rssi': u'Strong, 9', u'temp_bypass': u'0', u'type': 9, u'battery_ok': u'1', u'type_f': u'IR'}, u'RF:0409d730': {u'status': u'', u'name': u'Woonkamer achterzijde', u'zone': 2, u'area': 1, u'battery': u'', u'tamper': u'', u'cond_ok': u'1', u'su': 1, u'id': u'RF:0409d730', u'cond': u'', u'bypass': u'No', u'tamper_ok': u'1', u'rssi': u'Strong, 9', u'temp_bypass': u'0', u'type': 9, u'battery_ok': u'1', u'type_f': u'IR'}, u'RF:0279a070': {u'status': u'', u'name': u'Voordeur', u'zone': 5, u'area': 1, u'battery': u'', u'tamper': u'', u'cond_ok': u'1', u'su': 0, u'id': u'RF:0279a070', u'cond': u'', u'bypass': u'No', u'tamper_ok': u'1', u'rssi': u'Strong, 9', u'temp_bypass': u'0', u'type': 15, u'battery_ok': u'1', u'type_f': u'Keypad'}, u'RF:0434f900': {u'status': u'', u'name': u'Arjan', u'zone': 4, u'area': 1, u'battery': u'', u'tamper': u'', u'cond_ok': u'1', u'su': 0, u'id': u'RF:0434f900', u'cond': u'', u'bypass': u'No', u'tamper_ok': u'1', u'rssi': u'N/A', u'temp_bypass': u'0', u'type': 2, u'battery_ok': u'1', u'type_f': u'Remote Controller'}, u'RF:00f4fa10': {u'status': u'Door Close', u'name': u'Voordeur', u'zone': 6, u'area': 1, u'battery': u'', u'tamper': u'', u'cond_ok': u'1', u'su': 1, u'id': u'RF:00f4fa10', u'cond': u'', u'bypass': u'No', u'tamper_ok': u'1', u'rssi': u'Strong, 9', u'temp_bypass': u'0', u'type': 4, u'battery_ok': u'1', u'type_f': u'Door Contact'}})

**Comment by jeroenterheerdt** [comment]
@elpirato83 why is the output JSON? I cannot believe it is that way on your screen.

**Comment by jeroenterheerdt** [comment]
@elpirato83 also, are you sure the output of the status is just S? Because I tested it using the output you provided originally using Postman and I got Disarm. Can you post the output of panelcondget again?

**Comment by elpirato83** [comment]
This is the first time I'm running Python code from terminal, so maybe I'm doing something wrong. That's why I attached a screenshot from my terminal:

(Removed screenshot)

**Comment by elpirato83** [comment]
Postman output of panelcondget:

{
  "updates" : {
    "mode_a1" : "Disarm",
    "mode_a2" : "Disarm",
    "battery_ok" : "1",
    "battery" : "Normal",
    "tamper_ok" : "1",
    "tamper" : "N/A",
    "interference_ok" : "1",
    "interference" : "Normal",
    "ac_activation_ok" : "1",
    "ac_activation" : "Normal",
    "sys_in_inst": "System in maintenance",
    "rssi" : "1",
    "sig_gsm_ok" : "1",
    "sig_gsm" : "N/A"
  },
  "forms" : {
    "pcondform1" : {
      "mode" : "0",
      "f_arm" : "0"
    },
    "pcondform2" : {
      "mode" : "0",
      "f_arm" : "0"
    }
  }
}

**Comment by jeroenterheerdt** [comment]
thanks - care to pull and try again?

**Comment by elpirato83** [comment]
![2017-12-29 17_53_46-linux mint - vmware workstation](https://user-images.githubusercontent.com/34919058/34442284-642be82c-ecc1-11e7-90ec-5186386b2165.png)

**Comment by jeroenterheerdt** [comment]
Thanks. I still do not know why you get JSON output. The contents of the output is correct though.

**Comment by elpirato83** [comment]
The very first time I executed the test function I got error: No module named requests.
I had to try a few different ways to get this installed. Maybe this has something to do with it?

**Comment by jeroenterheerdt** [comment]
I doubt it, requests is a package that is required for the script to run.

**Comment by jeroenterheerdt** [comment]
@elpirato83 could you use Postman to do a POST request to your alarm control panel against `http://[ip]/action/panelCondPost` with basic auth (like you did when you did GET of `panelcondget`) and the following payload: `{'area': '1', 'mode': '4'}`. This should disarm your alarm. If not, please use developer tools to figure out which service is called when you switch status in your alarm. Please see the screenshot below - this is what I see when I just selected `Disarm` and `OK` on the left hand side. Under `Network` on the right hand side I see `panelCondPost` being called with the payload mentioned above. Depending on the browser you are using the UI might vary, but you should be able to see what is going on. Also, please test this for all states your alarm can be put in and report back. This allows us to fully support the GATE-03 system so your feedback is invaluable! Thanks!
![disarm](https://user-images.githubusercontent.com/8188990/34453327-4b41640e-ed52-11e7-84d9-ba62be4f6304.PNG)

**Comment by elpirato83** [comment]
@jeroenterheerdt http://[ip]/action/panelCondPost in Postman is working for parameters 'area': '1' and 'mode': '0' to 'mode': '4'.

'mode': '0' = Disarm
'mode': '1' = Full Arm
'mode': '2' = Home Arm 1
'mode': '3' = Home Arm 2
'mode': '4' = Home Arm 3

This is the response I receive each time after sending the command:
```
{
  "result" : 1,
  "message" : "Updated successfully."
}
```


![2017-12-30 21_13_04-alarm panel](https://user-images.githubusercontent.com/34919058/34457085-b6ef243a-eda6-11e7-8c20-7f7c966bd526.png)

**Comment by jeroenterheerdt** [comment]
@elpirato83 that is weird, because for the other three alarms mode 0 means arm away (full arm) and 4 is disarm. Anyway, I will update the code accordingly. Thanks.

**Comment by elpirato83** [comment]
I also noticed this difference. That's why I double checked the mode numbers before posting here😉

**Comment by jeroenterheerdt** [comment]
I have updated the code and pushed it to the Home Assistant repository. It will probably make it into the next release! Thanks and happy new year!

**Comment by elpirato83** [comment]
Thank you very much! I will test it as soon the next release is available and will keep you posted. Happy new year!

**Comment by jeroenterheerdt** [comment]
the new release is out, please open an new issue if anything is amiss.
