### ISSUE TITLE
Support for WV-1716

### ISSUE THREAD

**Issue by zumitnl** [jeroenterheerdt/python-egardia#15]
Hello,

I have the old Woonveilig box (WV-1716).
I've managed to make some small changes to support this one.
I've made some changes to egardiadevice.py
The diff file is attached.

Can you integrate this into newer versions?
If I have to test, I would like to help.

Kind Regards,

Sander Zumbrink

[egardiadevice.py.diff.txt](https://github.com/jeroenterheerdt/python-egardia/files/1716208/egardiadevice.py.diff.txt)

**Comment by jeroenterheerdt** [comment]
Please make a PR. Once integrated let's test it by running the test py files.

**Comment by zumitnl** [comment]
Hello Jeroen,

I've not worked with github before. So I don't know what you mean with make a PR.
I cloned the source, made the changes and tested it with the test commands.
How should I continu?

Kind Regards,

Sander Zumbrink

**Comment by zumitnl** [comment]
Hello Jeroen,

I've learned how to make a PR.
You should have received it.

Kind Regards,

Sander Zumbrink

**Comment by jeroenterheerdt** [comment]
Yep, got it. Will merge it and then we can do regular testing. thanks!
