### ISSUE TITLE
Status unknown

### ISSUE THREAD

**Issue by dreamfoxmedia** [jeroenterheerdt/python-egardia#17]
Egardia changed to unknown.
And on frontpage of HA is also displayes status: Unknown

**Comment by jeroenterheerdt** [comment]
@dreamfoxmedia please run `test_egardiadevice.py` in python3 and post the output.

**Comment by dreamfoxmedia** [comment]
@jeroenterheerdt 

 python3 test_egardiadevice.py -h 192.168.1.31 52010 username password GATE-03 ??
this does not work

documentation only say: usage: egardiaserver.py [-h] [-P PORT]

**Comment by jeroenterheerdt** [comment]
Run `test_egardiadevice.py - h` and look at the outout

**Comment by dreamfoxmedia** [comment]
python3 test_egardiadevice.py -h
usage: test_egardiadevice.py [-h] host port username password version

Run the test for EgardiaDevice

positional arguments:
  host        The IP of Egardia system
  port        The portnumber of Egardia system (default 80)
  username    The username for Egardia system
  password    The password for Egardia system
  version     The version of Egardia system (GATE-01, GATE-02 or GATE-03)

optional arguments:
  -h, --help  show this help message and exit

**Comment by jeroenterheerdt** [comment]
Yes, I know, I wrote the software😀, so please fill out the parameters as indicated and post the output.

**Comment by elpirato83** [comment]
Run this:
`python3 test_egardiadevice.py 192.168.1.31 80 USERNAME PASSWORD GATE-03`

Replace USERNAME and PASSWORD by your own credentials..

**Comment by dreamfoxmedia** [comment]
thanks @elpirato83 

@jeroenterheerdt :
Traceback (most recent call last):
  File "test_egardiadevice.py", line 85, in <module>
    main()
  File "test_egardiadevice.py", line 38, in main
    eg = e.EgardiaDevice(host, port, username, password, "", version)
  File "/home/pi/python-egardia-master(1)/python-egardia-master/src/pythonegardia/egardiadevice.py", line 47, in __init__
    self._sensors = self.getsensors()
  File "/home/pi/python-egardia-master(1)/python-egardia-master/src/pythonegardia/egardiadevice.py", line 108, in getsensors
    import requests
ImportError: No module named 'requests'

**Comment by jeroenterheerdt** [comment]
Please make sure to run this in the same virtual environment as home assistant or install the `requests` dependency (and possibly more).

**Comment by dreamfoxmedia** [comment]
@jeroenterheerdt 
pfff i was using hassio but yu suggeted to not use that because of its limitations.
So i did use hassbian now. how do i run that in "same virtual environment as home assistant" ?
as you noticed i'm not an expert so please be patient ;-)

**Comment by jeroenterheerdt** [comment]
have a look at the instructions on updating home assistant on how to enter the virtual environment or bite the bullet and do `sudo pip install requests` (or `sudo pip3` depending on your config). I personally do not like hassio for precisely this kind of stuff :)

**Comment by dreamfoxmedia** [comment]
@jeroenterheerdt  but i dont use hassio i use hassbian. Is HA also running on virtual here?

**Comment by jeroenterheerdt** [comment]
I know you use Hassbian. Please read the docs. You should kind of know what you are doing and where to find stuff in your environment, we cannot help you without that knowledge.

**Comment by dreamfoxmedia** [comment]
@jeroenterheerdt 
i',m learning ;-)


Getting STATE
getstate output  DISARM
------------
Getting SENSORS
getsensors output  {'RF:00ee1810': {'cond': '', 'tamper': '', 'tamper_ok': '1', 'battery': '', 'area': 1, 'cond_ok': '1', 'battery_ok': '1', 'rssi': 'Strong, 9', 'zone': 7, 'temp_bypass': '0', 'type': 'Door Contact', 'id': 'RF:00ee1810', 'status': 'Door Open', 'bypass': 'No', 'su': 1, 'name': 'Gameroom'}, 'RF:041f4e30': {'cond': '', 'tamper': '', 'tamper_ok': '1', 'battery': '', 'area': 1, 'cond_ok': '1', 'battery_ok': '1', 'rssi': 'Strong, 9', 'zone': 5, 'temp_bypass': '0', 'type': 'IR', 'id': 'RF:041f4e30', 'status': '', 'bypass': 'No', 'su': 1, 'name': 'Woonkamer'}, 'RF:04289130': {'cond': '', 'tamper': '', 'tamper_ok': '1', 'battery': '', 'area': 1, 'cond_ok': '1', 'battery_ok': '1', 'rssi': 'Strong, 9', 'zone': 4, 'temp_bypass': '0', 'type': 'IR', 'id': 'RF:04289130', 'status': '', 'bypass': 'No', 'su': 1, 'name': 'Workshopruimte'}, 'RF:00f36c10': {'cond': '', 'tamper': '', 'tamper_ok': '1', 'battery': '', 'area': 1, 'cond_ok': '1', 'battery_ok': '1', 'rssi': 'Strong, 9', 'zone': 6, 'temp_bypass': '0', 'type': 'Door Contact', 'id': 'RF:00f36c10', 'status': 'Door Close', 'bypass': 'No', 'su': 1, 'name': 'Voordeur'}, 'RF:00faa110': {'cond': '', 'tamper': '', 'tamper_ok': '1', 'battery': '', 'area': 1, 'cond_ok': '1', 'battery_ok': '1', 'rssi': 'Strong, 9', 'zone': 3, 'temp_bypass': '0', 'type': 'Door Contact', 'id': 'RF:00faa110', 'status': 'Door Close', 'bypass': 'No', 'su': 1, 'name': 'Achterdeur'}}
Selected random sensor:  RF:041f4e30
getsensor( RF:041f4e30 ) output  {'cond': '', 'tamper': '', 'tamper_ok': '1', 'battery': '', 'area': 1, 'cond_ok': '1', 'battery_ok': '1', 'rssi': 'Strong, 9', 'zone': 5, 'temp_bypass': '0', 'type': 'IR', 'id': 'RF:041f4e30', 'status': '', 'bypass': 'No', 'su': 1, 'name': 'Woonkamer'}
getsensorstate( RF:041f4e30 ) output  None
------------
IMPORTANT: continuing passed this point will arm and disarm your alarm!
Press y to ARM your alarm y
Sent arm command to alarm, waiting 10 seconds...
getstate output (should be ARM)  ARM
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  DISARM
Press y to HOME ARM your alarm y
Sent home arm command to alarm, waiting 10 seconds...
getstate output (should be HOME)  HOME
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  DISARM
Tests completed

**Comment by jeroenterheerdt** [comment]
You got it running perfectly! Thanks! This shows no error at all as far as I can see. Weird. Could you activate debug logging on home assistant and share Egardia related entries from the log?

**Comment by dreamfoxmedia** [comment]
@jeroenterheerdt : ok iT stills give unknown status when armed

![71f7f8ca-f83b-4af9-8aff-19ff13f1f31c](https://user-images.githubusercontent.com/5173591/37373569-71496062-2717-11e8-8b42-31286e11e69b.jpeg)

**Comment by jeroenterheerdt** [comment]
OK, so please enable debug logging on home assistant, look at the log and post anything relevant here. Also, let's have a final check at your config.

**Comment by thefoxmangit** [comment]
I have the same issue with my WV-1716, the Armed and Disarmed statuses are reported ok, but Arm Home is being reported as unknown. Is there anything I can do to provide you with debug info?

**Comment by jeroenterheerdt** [comment]
Please run the `test_egardiadevice.py ` as mentioned above and past the output here.

**Comment by thefoxmangit** [comment]
Thanks Jeroen, will do when i find some time.
I noticed this in the debug logging:

2018-03-15 23:08:37 INFO (SyncWorker_5) [pythonegardia.egardiadevice] Egardia alarm status: Home
2018-03-15 23:08:37 DEBUG (SyncWorker_5) [homeassistant.components.alarm_control_panel.egardia] Parsing status HOME
2018-03-15 23:08:37 DEBUG (SyncWorker_5) [homeassistant.components.alarm_control_panel.egardia] Not ignoring status HOME
2018-03-15 23:08:37 DEBUG (SyncWorker_5) [homeassistant.components.alarm_control_panel.egardia] newstatus None

So it seems that Pythonegardia finds the correct status but somehow the status is not correctly set by the homeassistant component.

**Comment by thefoxmangit** [comment]
i think the line:
'HOME': STATE_ALARM_ARMED_HOME

should be added to STATES in components/alarm_control_panel/egardia.py, but i do not know where to edit that file

**Comment by dreamfoxmedia** [comment]
its indeed only the armed home that gives unknown

**Comment by jeroenterheerdt** [comment]
Ah, I think I get it now. The config states 'armhome', but your alarm returns 'home'. What if you just change you config to 'home' instead of 'armhome'? This is not a fix for everyone else, but let's see if this resolves the problem. If it does we can fix it.

**Comment by thefoxmangit** [comment]
I am not running the pythonegardia server (need the Woonveilig functionality, so using their servers). Therefore, in my config I only have:

 egardia:
   host: YOUR_HOST
   username: YOUR_USERNAME
   password: YOUR_PASSWORD

should i add something there?

**Comment by jeroenterheerdt** [comment]
@fmslottje @dreamfoxmedia No, since you are not using Egardiaserver you cannot fix it on your own. I found the bug and will fix it probably tomorrow, it will take a while for the software to make it into the Home Assistant release. Out of curiosity, why are you not using Egardiaserver? You know you then do not need to pay the monthly subscription to woonveilig anymore, right? In other words, what do they offer that you want that you cannot get with Home Assistant?

**Comment by thefoxmangit** [comment]
Many thanks for folowing this up Jeroen, thats much appreciated. As an answer to your question, the main reason I continue to use the Woonveilig service instead of Egardiaserver is the fact that I want to be able to arm and disarm my alarm from 4G connections, while not exposing my home assistant system to the internet. Maybe i'm naïve, but I would expect Woonveilig to be better in control of security of their servers than I will be securing my raspberry pi. 

Further, the fact that the Woonveilig system does the regular system checks from outside (which would require a separate sever outside the network to mimic) and provides a service where the system performs phone calls in the event of an alarm are plusses.

**Comment by jeroenterheerdt** [comment]
@fmslottje system checks will still continue. Calling yourself can also be done using HA. I personally think I am better at monitoring my safety than woonveilig is - I work in IT, so I know a little bit about this. Also the price for something that hopefully never happens is steep. Making HA accessible to the internet is one of things that are most useful about it in the first place! So, no, no reason for me to keep the woonveilig subscription. Anything you can dream up you can build using HA. Again, that might not be true for you - suite yourself, I just wanted to make sure you are not deciding to (not) do something because of incomplete information :)

**Comment by jeroenterheerdt** [comment]
closing this issue since it is fixed and will be merged in a future release of HA - discussion can continue if you want.

**Comment by dreamfoxmedia** [comment]
Thank you for the help
