### ISSUE TITLE
Showing if a door is open or close

### ISSUE THREAD

**Issue by dreamfoxmedia** [jeroenterheerdt/python-egardia#18]
Hello,

Its not an issue but a question. 
I'm trying for days now how to display a sensor that tells me if a door is open or closed.
Can you point me in the right directions or give an example?

**Comment by jeroenterheerdt** [comment]
Are you using a door contact sensor from woonveilig? If so with the last update of HA the sensor is already there, but hidden. You can find it in the states list.

**Comment by dreamfoxmedia** [comment]
How can i not hide this then?

Now i used:
    sensors:
      voordeur:
          value_template: >-
            {%- if is_state("binary_sensor.voordeur", "on") -%}
            Open
            {%- else -%}
            Dicht
            {%- endif -%}

and that works for me

**Comment by jeroenterheerdt** [comment]
Sure, but you could also specify `hidden: false` in `customize.yaml`. Or use the group visibility functionality: https://www.home-assistant.io/docs/configuration/group_visibility/#changing-visibility-of-a-group
