### ISSUE TITLE
Not working with GATE-03 anymore

### ISSUE THREAD

**Issue by Jjesper** [jeroenterheerdt/python-egardia#19]
Hi,

Since some update a while ago, Egardia changed it's default login (admin/admin123) for the WebPanel.
I contacted their support but they were not willing to give me the credentials.

Anyway, they told me the reporting address was ics.alt.egardia.com, so I "tricked" my alarm into letting believe that specific dns name would be an internal IP.

Anyway, it resolved to my computer which was running the python script to fetch the codes on port 52010.

The funny thing was, that the python script was only gathering the same code for each action, I disarmed it, partially armed it, fully armed it, pressed the help button on the remote, trigged the alarm and so on (according to the guide I should get a code for each different action).

This is the output, where i replaced the status codes, but they were all identical

__main__    : INFO     Server listening on ('', 52010)
__main__    : INFO     Starting server ('', 52010)
__main__    : DEBUG    Received new status code from alarm system: 1XXXXXXXXXXX1
__main__    : DEBUG    Notify callback with data: {'status': '1XXXXXXXXXXX1'}
event:  {'status': '1XXXXXXXXXXX1'}
__main__    : DEBUG    Received new status code from alarm system: 1XXXXXXXXXXX1
__main__    : DEBUG    Received new status code from alarm system: 1XXXXXXXXXXX1
__main__    : DEBUG    Received new status code from alarm system: 1XXXXXXXXXXX1
__main__    : DEBUG    Received new status code from alarm system: 1XXXXXXXXXXX1
__main__    : DEBUG    Received new status code from alarm system: 1XXXXXXXXXXX1

I tried posting this on the hass community, but was not able to get a verification email.
I tried the other python scripts, including my egardia credentials, but also no luck.

If you need anything, I'd happy to help out testing.

**Comment by jeroenterheerdt** [comment]
So.... Basically your f##ked. I mean, if you cannot login to the local IP it will be almost ubdoable to make this work again. Could you revert to an older version? Also, what errors did you get running the other scripts?

**Comment by jeroenterheerdt** [comment]
Closing this issue, let me know if you need more help.

**Comment by Dr-Eye** [comment]
If you want to reset it to stock setting do this:

Power down the device, disable the battery.
Press and hold the Confirm button on the device and switch it back on.
Keep holding the Confirm button (It will start beeping loudly at one point, but keep pressing the button till the device reboots)
After that you can login using admin/admin1234
It will loose the connection to egardia but you have access again.
