### ISSUE TITLE
Different arm/disarm mode numbers

### ISSUE THREAD

**Issue by burodevelopment** [jeroenterheerdt/python-egardia#2]
Hi Jeroen,

Did a quick test and found that my Egardia uses different arm/disarm mode numbers:

0 - disarm
1 - arm
2 - home arm

Maybe this depends on the model of the base unit(?). I have a GATE-02.

**Comment by jeroenterheerdt** [comment]
yes - that might be the case. I have a GATE-01 so I cannot test. You might have more luck using the egardiaserver component by the way.

**Comment by jeroenterheerdt** [comment]
Closing because of limitation.
