### ISSUE TITLE
States of door contacts connected to GATE-02 not updating

### ISSUE THREAD

**Issue by ronaldbijlhouwer** [jeroenterheerdt/python-egardia#20]
Hi @jeroenterheerdt. I am new to this channel. I have connected my GATE-02 to HASS and noticed the states of my door contacts in HASS are not updating. I had a look at the getsensorstate code and noticed the GATE-03 support in there. When I compare that with the output I'm getting from deviceListGet on my GATE-02 (status is 'Door Open' or 'Door Closed'), I think the same logic for door sensors on GATE-03 might also need to be applied for GATE-02. Can this be the case? Please let me know if you want me to run some tests. Thanks!

**Comment by jeroenterheerdt** [comment]
@ronaldbijlhouwer please run the provided `test_xxx.py` scripts and paste the output here.

**Comment by ronaldbijlhouwer** [comment]
Output from test_egardiadevice.py:

Getting STATE
getstate output  ES
------------
Getting SENSORS
getsensors output  {'PF:01': {'area': 1, 'zone': 71, 'type': 25, 'type_f': 'Power Switch', 'name': 'Stekker camera woonkamer', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Off', 'id': 'PF:01', 'su': 1}, 'PF:02': {'area': 1, 'zone': 72, 'type': 25, 'type_f': 'Power Switch', 'name': 'Stekker lamp woonkamer voorraam', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Off', 'id': 'PF:02', 'su': 1}, 'PF:03': {'area': 1, 'zone': 73, 'type': 25, 'type_f': 'Power Switch', 'name': 'Stekker lamp woonkamer zijraam', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 6', 'status': 'Off', 'id': 'PF:03', 'su': 1}, 'RF:002906b0': {'area': 1, 'zone': 14, 'type': 45, 'type_f': 'Siren', 'name': 'Binnensirene', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 8', 'status': '', 'id': 'RF:002906b0', 'su': 1}, 'RF:005e5610': {'area': 1, 'zone': 10, 'type': 4, 'type_f': 'Door Contact', 'name': 'Raamcontact huiskamer rechts', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:005e5610', 'su': 1}, 'RF:005f3210': {'area': 1, 'zone': 5, 'type': 4, 'type_f': 'Door Contact', 'name': 'Raamcontact slaapkamer links', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 7', 'status': 'Door Close', 'id': 'RF:005f3210', 'su': 1}, 'RF:00635410': {'area': 1, 'zone': 9, 'type': 4, 'type_f': 'Door Contact', 'name': 'Raamcontact huiskamer voor', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:00635410', 'su': 1}, 'RF:0066cc10': {'area': 1, 'zone': 11, 'type': 4, 'type_f': 'Door Contact', 'name': 'Deurcontact huiskamer rechts', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Open', 'id': 'RF:0066cc10', 'su': 1}, 'RF:00677110': {'area': 1, 'zone': 6, 'type': 4, 'type_f': 'Door Contact', 'name': 'Raamcontact badkamer', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 8', 'status': 'Door Close', 'id': 'RF:00677110', 'su': 1}, 'RF:0067e810': {'area': 1, 'zone': 13, 'type': 4, 'type_f': 'Door Contact', 'name': 'Raamcontact huiskamer links', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:0067e810', 'su': 1}, 'RF:00689010': {'area': 1, 'zone': 12, 'type': 4, 'type_f': 'Door Contact', 'name': 'Deurcontact huiskamer links', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:00689010', 'su': 1}, 'RF:006afb10': {'area': 1, 'zone': 4, 'type': 4, 'type_f': 'Door Contact', 'name': 'Raamcontact slaapkamer rechts', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:006afb10', 'su': 1}, 'RF:0248d970': {'area': 1, 'zone': 8, 'type': 15, 'type_f': 'Keypad', 'name': 'Bedieningspaneel', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 8', 'status': '', 'id': 'RF:0248d970', 'su': 0}, 'RF:02949f30': {'area': 1, 'zone': 7, 'type': 9, 'type_f': 'IR', 'name': 'Bewegingsmelder schuur', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Good, 5', 'status': '', 'id': 'RF:02949f30', 'su': 1}, 'RF:67a50200': {'area': 1, 'zone': 3, 'type': 2, 'type_f': 'Remote Controller', 'name': 'Afstandsbediening 2', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': '', 'id': 'RF:67a50200', 'su': 0}, 'RF:6b860040': {'area': 1, 'zone': 15, 'type': 11, 'type_f': 'Smoke Detector', 'name': 'Rookmelder meterkast', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': '', 'id': 'RF:6b860040', 'su': 1}, 'RF:a9860040': {'area': 1, 'zone': 2, 'type': 11, 'type_f': 'Smoke Detector', 'name': 'Rookmelder zolder', 'cond': 'Out Of Order', 'cond_ok': '0', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'N/A', 'status': '', 'id': 'RF:a9860040', 'su': 1}, 'RF:f4ab0200': {'area': 1, 'zone': 1, 'type': 2, 'type_f': 'Remote Controller', 'name': 'Afstandsbediening 1', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': '', 'id': 'RF:f4ab0200', 'su': 0}}
Selected random sensor:  RF:00677110
getsensor( RF:00677110 ) output  {'area': 1, 'zone': 6, 'type': 4, 'type_f': 'Door Contact', 'name': 'Raamcontact badkamer', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 8', 'status': 'Door Close', 'id': 'RF:00677110', 'su': 1}
getsensorstate( RF:00677110 ) output  False
------------
IMPORTANT: continuing passed this point will arm and disarm your alarm!
Press y to ARM your alarm y
Sent arm command to alarm, waiting 10 seconds...
getstate output (should be ARM)  ES
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  ES
Press y to HOME ARM your alarm y
Sent home arm command to alarm, waiting 10 seconds...
getstate output (should be HOME)  ES
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  ES
Tests completed

**Comment by jeroenterheerdt** [comment]
weird - is the state of the alarm panel being correctly represented in Home Assistant? Since the final part of the test seems to return 'ES' all the time... what is the output when you call `panelCondGet` with for example postman? Also, if you would change the code [here](https://github.com/jeroenterheerdt/python-egardia/blob/master/src/pythonegardia/egardiadevice.py#L176) to read: `elif self._version == "GATE-03" or self._version == "GATE-02":` and [here](https://github.com/jeroenterheerdt/python-egardia/blob/master/src/pythonegardia/egardiadevice.py#L169) to read: `if self._version in ["WV-1716", "GATE-01"]:`, does that give better results in the state of sensors in Home Assistant? Basically you would be switching the logic around as you suggested. Let me know if that works or make a PR with that fix.

**Comment by ronaldbijlhouwer** [comment]
When pressing y to ARM the alarm, it actually get disarmed. When I press y to DISARM the alarm, it gets home armed, when I press y to HOME ARM, it gets (fully) armed and when I press y to DISARM the alarm again, it gets home armed again.

**Comment by jeroenterheerdt** [comment]
@ronaldbijlhouwer when you say 'it gets ...' do you mean you hear the correct sounds or also that the status in HA is updated correctly?

**Comment by ronaldbijlhouwer** [comment]
I can tell when the alarm is getting disarmed or armed because I can hear the correct sounds and the alarm status is updated on the mobile Woonveilig app.

**Comment by jeroenterheerdt** [comment]
and.... on the Home Assistant side?

**Comment by ronaldbijlhouwer** [comment]
I will need to check that later on.

**Comment by jeroenterheerdt** [comment]
@ronaldbijlhouwer ok, please do, also please make the changes I suggested above. If it helps, please create a PR for the fixes.

**Comment by ronaldbijlhouwer** [comment]
@jeroenterheerdt On Home Assistant the state of alarm_control_panel.egardia is unknown.

**Comment by ronaldbijlhouwer** [comment]
Postman output panelCondGet:

{
    "updates": {
        "mode_a1": "Disarm",
        "mode_a2": "Disarm",
        "battery_ok": "1",
        "battery": "Normal",
        "tamper_ok": "1",
        "tamper": "N/A",
        "interference_ok": "1",
        "interference": "Normal",
        "ac_activation_ok": "1",
        "ac_activation": "Normal",
        "sys_in_inst": "System in maintenance",
        "rssi": "1",
        "sig_gsm_ok": "1",
        "sig_gsm": "N/A"
    },
    "forms": {
        "pcondform1": {
            "mode": "0",
            "f_arm": "0"
        },
        "pcondform2": {
            "mode": "0",
            "f_arm": "0"
        }
    }
}

**Comment by ronaldbijlhouwer** [comment]
Do I need to apply the suggested code changes on my HASS instance? Not sure how to do that. I'm running Hass.io.

**Comment by jeroenterheerdt** [comment]
OK, that makes sense. So, two problems:  the state not getting reported correctly and the sensors not being updated. Let me create a new version for you with which you can test.

**Comment by jeroenterheerdt** [comment]
@ronaldbijlhouwer I have looked at the situation and it seems like the output that your system returns is the same as my GATE-03 system. Also, other users have tested this with GATE-02. Are you absolutely certain you have a GATE-02? Please run the tests specifying GATE-03 as the type and post the results here.

**Comment by ronaldbijlhouwer** [comment]
Yes, it is definitely a GATE-02.
![gate-02](https://user-images.githubusercontent.com/40568921/41929261-ca13dd78-7977-11e8-8dbc-2bd97fc12c7d.jpg)

**Comment by ronaldbijlhouwer** [comment]
Output from test_egardiadevice.py when specifying GATE-03.

Getting STATE
getstate output  DISARM
------------
Getting SENSORS
getsensors output  {'PF:01': {'area': 1, 'zone': 71, 'type': 'Power Switch', 'name': 'Stekker camera woonkamer', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 7', 'status': 'Off', 'id': 'PF:01', 'su': 1}, 'PF:02': {'area': 1, 'zone': 72, 'type': 'Power Switch', 'name': 'Stekker lamp woonkamer voorraam', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Off', 'id': 'PF:02', 'su': 1}, 'PF:03': {'area': 1, 'zone': 73, 'type': 'Power Switch', 'name': 'Stekker lamp woonkamer zijraam', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 7', 'status': 'Off', 'id': 'PF:03', 'su': 1}, 'RF:002906b0': {'area': 1, 'zone': 14, 'type': 'Siren', 'name': 'Binnensirene', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': '', 'id': 'RF:002906b0', 'su': 1}, 'RF:005e5610': {'area': 1, 'zone': 10, 'type': 'Door Contact', 'name': 'Raamcontact huiskamer rechts', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:005e5610', 'su': 1}, 'RF:005f3210': {'area': 1, 'zone': 5, 'type': 'Door Contact', 'name': 'Raamcontact slaapkamer links', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 6', 'status': 'Door Open', 'id': 'RF:005f3210', 'su': 1}, 'RF:00635410': {'area': 1, 'zone': 9, 'type': 'Door Contact', 'name': 'Raamcontact huiskamer voor', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:00635410', 'su': 1}, 'RF:0066cc10': {'area': 1, 'zone': 11, 'type': 'Door Contact', 'name': 'Deurcontact huiskamer rechts', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Open', 'id': 'RF:0066cc10', 'su': 1}, 'RF:00677110': {'area': 1, 'zone': 6, 'type': 'Door Contact', 'name': 'Raamcontact badkamer', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Open', 'id': 'RF:00677110', 'su': 1}, 'RF:0067e810': {'area': 1, 'zone': 13, 'type': 'Door Contact', 'name': 'Raamcontact huiskamer links', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:0067e810', 'su': 1}, 'RF:00689010': {'area': 1, 'zone': 12, 'type': 'Door Contact', 'name': 'Deurcontact huiskamer links', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Close', 'id': 'RF:00689010', 'su': 1}, 'RF:006afb10': {'area': 1, 'zone': 4, 'type': 'Door Contact', 'name': 'Raamcontact slaapkamer rechts', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 8', 'status': 'Door Close', 'id': 'RF:006afb10', 'su': 1}, 'RF:02949f30': {'area': 1, 'zone': 7, 'type': 'IR', 'name': 'Bewegingsmelder schuur', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Good, 4', 'status': '', 'id': 'RF:02949f30', 'su': 1}, 'RF:6b860040': {'area': 1, 'zone': 15, 'type': 'Smoke Detector', 'name': 'Rookmelder meterkast', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': '', 'id': 'RF:6b860040', 'su': 1}, 'RF:a9860040': {'area': 1, 'zone': 2, 'type': 'Smoke Detector', 'name': 'Rookmelder zolder', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'N/A', 'status': '', 'id': 'RF:a9860040', 'su': 1}}
Selected random sensor:  RF:00677110
getsensor( RF:00677110 ) output  {'area': 1, 'zone': 6, 'type': 'Door Contact', 'name': 'Raamcontact badkamer', 'cond': '', 'cond_ok': '1', 'battery': '', 'battery_ok': '1', 'tamper': '', 'tamper_ok': '1', 'bypass': 'No', 'temp_bypass': '0', 'rssi': 'Strong, 9', 'status': 'Door Open', 'id': 'RF:00677110', 'su': 1}
getsensorstate( RF:00677110 ) output  True
------------
IMPORTANT: continuing passed this point will arm and disarm your alarm!
Press y to ARM your alarm y
Sent arm command to alarm, waiting 10 seconds...
getstate output (should be ARM)  ARM
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  DISARM
Press y to HOME ARM your alarm y
Sent home arm command to alarm, waiting 10 seconds...
getstate output (should be HOME)  HOME
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  DISARM
Tests completed

**Comment by jeroenterheerdt** [comment]
For now, if you configure Hass to run in GATE-03 setting does the status show up correctly (I assume yes) and do the sensors work correctly too?

**Comment by ronaldbijlhouwer** [comment]
Yes, that seems to do the trick! Both the alarm control panel and the sensors now show the correct state. 😄

**Comment by jeroenterheerdt** [comment]
OK, I'll leave the code like this but will make a note in the docs here and on HA that you might have to use GATE-03 instead of GATE-02 since other users are using the code as-is with GATE-02s successfully.

**Comment by ronaldbijlhouwer** [comment]
Ok, that's fine. Thanks for looking into this. Much appreciated!
