### ISSUE TITLE
Server polling

### ISSUE THREAD

**Issue by tkvw** [jeroenterheerdt/python-egardia#25]
I am in progress of including my Woonveilig (GATE-03) in home assistant. Your library and the egardia component is excellent, thanks for the good work! I can't get the EgardiaServer to work; no reports are send from the AlarmPanel. Maybe there is something updated on the firmware or whatever. I've checked the sources of your library and I am wondering why you didn't include a polling method for events. The alarm panel does have a endpoints (`logsGet` and `recordListGet`) to get the current state and triggering of alarms. With a polling of 1 second when the alarm is armed there shouldn't be a huge delay. 

I know you don't use the device anymore and I am willing to create a PR, just curious as to why you've didn't include it?

**Comment by jeroenterheerdt** [comment]
When I still owned the device the method I implemented worked as was the easiest, also I remember the endpoints not providing all info needed or being slow to update. It seems like they plugged the hole that enabled the scenario I used since then.

**Comment by bart-roos** [comment]
@tkvw Have you ever gotten around to write some code to implement the polling? I was facing the same issue and fixed the EgardiaServer communication by disabling the XMPP communication to Woonveilig. However, by doing that controlling the alarm system through the Woonveilig app and website breaks completely. Using the polling mechanism would be a great workaround for this issue.
