### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by fabaff** [jeroenterheerdt/python-egardia#27]
`setup.py`: 1.0.40, https://github.com/jeroenterheerdt/python-egardia/blob/master/src/setup.py#L4
PyPI: 1.0.50, https://pypi.org/project/pythonegardia/ 

Would be nice if it's aligned as this may cause issues for distributions. Thanks

**Comment by jeroenterheerdt** [comment]
thanks - I hope I fixed it this time :)
