### ISSUE TITLE
The README.md points to home-assistant.io instead of https://home-assistant.io//

### ISSUE THREAD

**Issue by jpluimers** [jeroenterheerdt/python-egardia#30]
I will send a pull-request for this shortly.

In the current [README.md](https://github.com/jeroenterheerdt/python-egardia/blob/6168d0fcf9902b1a7f12ccc7cc5a235122faa269/README.md), the first link causes a 404-error as it is `[Home Assistant](home-assistant.io)` and should become `[Home Assistant](https://home-assistant.io/)`.

**Comment by jeroenterheerdt** [comment]
thanks!

**Comment by jpluimers** [comment]
> thanks!

No problem.
