### ISSUE TITLE
Support for SmartHome

### ISSUE THREAD

**Issue by tristangrichard** [jeroenterheerdt/python-egardia#35]
Hi, 

I am trying to integrate my SmartHome central in HA. Looks like [this](https://www.climax.com.tw/new/downloads/VL%20Touchscreen%20Alarm_20190104.pdf)

Has anyone successfully connected to this alarm?

**Comment by tristangrichard** [comment]
@jeroenterheerdt 
Any chance we could have talk?
I would like to contribute to the Egardia integration

**Comment by jeroenterheerdt** [comment]
feel free to open a PR or even better, I am happy for you to take over the work in its entirety. I no longer own an Egardia alarm system, so I cannot fix bugs or add new functionality.

**Comment by tristangrichard** [comment]
I basically need to update the HA integration to handle different languages I think, but I don't know where to start and how to test it with my HA instance

**Comment by tristangrichard** [comment]
@jeroenterheerdt Created a [PR](https://github.com/jeroenterheerdt/python-egardia/pull/36)

**Comment by jeroenterheerdt** [comment]
thank you, I don't have an Egardia alarm any more, so I cannot test it. I will merge you PR.

**Comment by tristangrichard** [comment]
@jeroenterheerdt  I tested it against mine and it worked just fine.
Do you know when it will be available in HA?

**Comment by tristangrichard** [comment]
@jeroenterheerdt what are the steps to get this in HA?
