### ISSUE TITLE
When Armed, status shown in Home Assistant reverts back to unarmed after a while.

### ISSUE THREAD

**Issue by jeroenterheerdt** [jeroenterheerdt/python-egardia#4]
see title.

**Comment by jeroenterheerdt** [comment]
Traced to system tests happening. Will need to ignore that status codes. Also, multiple arm and disarm codes need to be accepted to cover for multiple users.

**Comment by jeroenterheerdt** [comment]
Closing issue, fixed in above mentioned PR.

**Comment by ufulu** [comment]
quick question: how to I find out which system test status codes are being used and need to be set on the ignore list? 
Cheers!

**Comment by jeroenterheerdt** [comment]
They should be logged by ergardiaserver
________________________________
