### ISSUE TITLE
No module named 'homeassistant'

### ISSUE THREAD

**Issue by ufulu** [jeroenterheerdt/python-egardia#7]
First of all, thank you for your work! I really appreciate it and I am looking forward to integrating my egardia system into home assistant. Currently I have an issue though. When I run egardiaserver.py I get the following error:  
File "/usr/local/lib/python3.6/site-packages/pythonegardia/egardiaserver.py", line 9, in <module>
    import homeassistant.remote as remote
ModuleNotFoundError: No module named 'homeassistant'

I am running the python script from within the latest homeassistant docker container.
Any idea what could be causing the issue? Thank you in advance for your support!

**Comment by Daehnie** [comment]
Try 'pip3 install homeassistant'.
If you succesfully install your egardiaserver, please tell me how did you log your real-time Servercodes into a text file.

**Comment by ufulu** [comment]
Thank you so much @Daehnie. I feel so stupid. :( I now have my servercodes, although I also have the issue, that they only end up in the log after I exit egardiaserver.py.
